-- CreateTable
CREATE TABLE "CooperationRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyName" TEXT NOT NULL,
    "contactName" TEXT NOT NULL,
    "contactEmail" TEXT NOT NULL,
    "contactPhone" TEXT NOT NULL DEFAULT '',
    "raceTitle" TEXT NOT NULL,
    "raceSummary" TEXT NOT NULL,
    "taskDescription" TEXT NOT NULL,
    "trainingDataSummary" TEXT NOT NULL DEFAULT '',
    "evaluationNotes" TEXT NOT NULL,
    "keywordsText" TEXT NOT NULL,
    "signupStart" TEXT NOT NULL,
    "signupEnd" TEXT NOT NULL,
    "raceStart" TEXT NOT NULL,
    "raceEnd" TEXT NOT NULL,
    "tokenLimit" INTEGER NOT NULL DEFAULT 4000,
    "maxTeamSize" INTEGER NOT NULL DEFAULT 5,
    "submissionIntervalHours" INTEGER NOT NULL DEFAULT 24,
    "freezeMinutesBeforeEnd" INTEGER NOT NULL DEFAULT 30,
    "hasTrainingData" BOOLEAN NOT NULL DEFAULT true,
    "enableFreeze" BOOLEAN NOT NULL DEFAULT true,
    "displayShowTrainingData" BOOLEAN NOT NULL DEFAULT true,
    "displayShowOrganizerComment" BOOLEAN NOT NULL DEFAULT true,
    "displayShowTopHighlights" BOOLEAN NOT NULL DEFAULT true,
    "displayShowRiderCode" BOOLEAN NOT NULL DEFAULT true,
    "taskPackageFileName" TEXT NOT NULL DEFAULT '',
    "taskPackageFilePath" TEXT NOT NULL DEFAULT '',
    "proposalFileName" TEXT NOT NULL DEFAULT '',
    "proposalFilePath" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
